/*
 * Copyright 2013 Modeliosoft
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */  
                                    

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.08 at 06:09:31 PM CEST
//
package org.modelio.gproject.data.module.jaxbv2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for _PropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_PropertyType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence minOccurs="0">
 * &lt;element name="Jxbv2Enumeration" type="{}_Enumeration" minOccurs="0"/>
 * &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="type" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Boolean"/>
 * &lt;enumeration value="Date"/>
 * &lt;enumeration value="Element"/>
 * &lt;enumeration value="Float"/>
 * &lt;enumeration value="Integer"/>
 * &lt;enumeration value="MultiText"/>
 * &lt;enumeration value="RichText"/>
 * &lt;enumeration value="Text"/>
 * &lt;enumeration value="Time"/>
 * &lt;enumeration value="Unsigned"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("25f3a4eb-a813-4f07-b2ca-ea5adef9b145")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_PropertyType", propOrder = {
    "enumeration",
    "description"
})
public class Jxbv2PropertyType {
    @objid ("e87762cb-1385-409a-b4ef-496ef596d6cf")
    @XmlElement(name = "Description")
    protected String description;

    @objid ("ff9b42a0-584f-463e-8415-ac222b21f31b")
    @XmlAttribute(name = "id", required = true)
    protected String id;

    @objid ("59310f6d-e71b-4ae9-bf0a-d284942a091d")
    @XmlAttribute(name = "type", required = true)
    protected String type;

    @objid ("e53e99ba-0367-499b-83b1-b89501770356")
    @XmlAttribute(name = "uid")
    protected String uid;

    @objid ("202f8711-0af1-4991-b40a-4a356f7b31b5")
    @XmlElement(name = "Enumeration")
    protected Jxbv2Enumeration enumeration;

    /**
     * Gets the value of the enumeration property.
     * @return
     * possible object is
     * {@link Jxbv2Enumeration }
     */
    @objid ("0756ae75-3396-4206-b37c-3964afbadefd")
    public Jxbv2Enumeration getEnumeration() {
        return this.enumeration;
    }

    /**
     * Sets the value of the enumeration property.
     * @param value allowed object is
     * {@link Jxbv2Enumeration }
     */
    @objid ("11c531c5-2c6f-4d75-981b-acdc8ff8f25c")
    public void setEnumeration(Jxbv2Enumeration value) {
        this.enumeration = value;
    }

    /**
     * Gets the value of the description property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("23b15038-255e-4024-a028-3935743ad918")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of the description property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("69928021-37dd-42e9-9296-14b4ad0f3f93")
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the id property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("0dbdf70a-94f6-48b2-aabe-0e1422acd418")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("d13eefff-12a4-4143-9cb4-8b3ed2208f1d")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("b68707a5-6fda-4cbd-8045-cc6521351380")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of the type property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("4e2ed608-fd74-4cef-a8e6-df1739168d4c")
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the uid property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("1bd4a777-6ee2-4cfd-8d03-2810a15ef13d")
    public String getUid() {
        return this.uid;
    }

    /**
     * Sets the value of the uid property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("f8caceee-9cce-4874-b01a-7648fe291427")
    public void setUid(String value) {
        this.uid = value;
    }

}
