/*
 * Copyright 2013 Modeliosoft
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */  
                                    

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.08 at 06:09:31 PM CEST
//
package org.modelio.gproject.data.module.jaxbv2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for _Literal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_Literal">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("5cc0e493-5acc-439e-9e5e-e66f95364c12")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_Literal")
@XmlSeeAlso({
    org.modelio.gproject.data.module.jaxbv2.Jxbv2Enumeration.Jxbv2Literal.class
})
public class Jxbv2Literal {
    @objid ("6c6b1328-c7f4-428f-91f2-b1a43b78d589")
    @XmlAttribute(name = "value", required = true)
    protected String value;

    @objid ("05ec6953-23e3-4507-9a7d-0bc0f740b93e")
    @XmlAttribute(name = "label")
    protected String label;

    /**
     * Gets the value of the value property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("780b1425-d12d-4e27-93b2-4a8f116dc764")
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of the value property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("7ebcccd3-8324-4eaf-b9a7-2e25ef17d32f")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the label property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("f753b2e2-2388-46f5-9532-4ea86726ad33")
    public String getLabel() {
        return this.label;
    }

    /**
     * Sets the value of the label property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("e4419d10-16c1-4eb6-960f-259006463265")
    public void setLabel(String value) {
        this.label = value;
    }

}
