/*
 * Copyright 2013 Modeliosoft
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */  
                                    

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.08 at 06:09:31 PM CEST
//
package org.modelio.gproject.data.module.jaxbv2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for _ExternDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_ExternDocumentType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="is-hidden" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("105d3538-9518-493d-961c-f254276f44da")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_ExternDocumentType")
public class Jxbv2ExternDocumentType {
    @objid ("a602e92a-6646-4a74-be5c-fe4d7501093a")
    @XmlAttribute(name = "name", required = true)
    protected String name;

    @objid ("ab4aa660-eafe-4611-a03c-d38454883fdd")
    @XmlAttribute(name = "uid")
    protected String uid;

    @objid ("b76ff7d3-13e3-4b65-8406-68972d4190b6")
    @XmlAttribute(name = "label")
    protected String label;

    @objid ("505e6649-5665-4d43-936f-b7496b98009a")
    @XmlAttribute(name = "is-hidden")
    protected String isHidden;

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("6e81968f-2a41-4b7d-86d2-360f0e67a923")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("b00c5c1c-f150-49dd-85f6-cebd2c8adc63")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the uid property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("ef281c53-2efb-40cc-9854-8634dd7d0721")
    public String getUid() {
        return this.uid;
    }

    /**
     * Sets the value of the uid property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("a7dae9af-9e02-4174-81e2-8d95cc5fde58")
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the label property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("395785dc-1be1-41b5-9818-7ef4f194dae6")
    public String getLabel() {
        return this.label;
    }

    /**
     * Sets the value of the label property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("3e9c446d-bd12-4fc7-9150-fc3089a21961")
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the isHidden property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("e14b3b4c-7174-4fe1-839b-1401195a8e4e")
    public String getIsHidden() {
        return this.isHidden;
    }

    /**
     * Sets the value of the isHidden property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("f31b908d-4f7f-4148-9db3-c68d57608c51")
    public void setIsHidden(String value) {
        this.isHidden = value;
    }

}
